const { plugin } = require('../dist/index.js');
const { buildSchema, parse } = require('graphql');
const fs = require('fs');

const schema = buildSchema(fs.readFileSync('./schema.graphql', 'utf8'));
const documents = [{
  document: parse(fs.readFileSync('./queries.graphql', 'utf8'))
}];

const config = {
  withHooks: true,
  urqlImportFrom: 'solid-urql'
};

const output = plugin(schema, documents, config);

console.log('// Generated by typescript-solid-urql plugin\n');
console.log(output.prepend.join('\n'));
console.log('\n');
console.log(output.content);
