name: release
on:
  pull_request: # for snapshot release
    branches:
      - main

  push: # for stable release
    branches:
      - main

jobs:
  release-snapshot:
    if: github.event_name == 'pull_request'
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    permissions:
      id-token: write # allows ODIC publishing
      pull-requests: write # allows creating comment with alpha versions
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 24
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: FILLER

  release-stable:
    if: github.event_name == 'push'
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    permissions:
      id-token: write # allows ODIC publishing
      contents: write
    with:
      releaseScript: release
      nodeVersion: 24
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: FILLER
